--- #YAML:1.0
name:               AutoLoader
version:            5.70
abstract:           load subroutines only on demand
author:
    - Steffen Mueller <smueller@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
resources:
    bugtracker:   http://rt.perl.org/perlbug/
    MailingList:  http://lists.cpan.org/showlist.cgi?name=perl5-porters
    repository:   git://perl5.git.perl.org/perl.git perl-git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
