--- #YAML:1.0
name:                AutoLoader
version:             5.65
abstract:            load subroutines only on demand
license:             perl
author:              
    - Steffen Mueller <smueller@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
